### ISSUE TITLE
Use proper XML library

### ISSUE THREAD

**Issue by robertvazan** [jirkapinkas/jsitemapgenerator#6]
Parameter separator (`&`) in an URL will be literally written into the output, producing malformed XML. There are likely many other issues with such hand-coded XML serialization. You should use some existing XML library like [jdom2](http://www.studytrails.com/java/xml/jdom2/java-xml-jdom2-introduction/) or even the built-in Java XML API.

**Comment by jirkapinkas** [comment]
fixed malformed XML, but won't use any library, because: 

1. In the past I wanted to rewrite jsitemapgenerator to use JAXB, but in Java 9 JAXB was removed from Java core.
2. I want to minimize number of dependencies, zero dependencies is for this kind of library ideal
3. And last: I would have to rewrite tests and I don't really want to do that
